print('Today\'s Date?')
date = input()
print('Breakfast calories?')
brcal = int(input())
print('Lunch calories?')
lucal = int(input())
print('Dinner calories?')
dical = int(input())
print('Snack calories?')
sncal = int(input())
calcsum = str(brcal + lucal + dical + sncal)
print('Calorie content for ' + date + ': ' + calcsum)