SELECT TOP (100) [CustomerKey]
      ,[GeographyKey]
      ,[CustomerAlternateKey]
      ,[Title]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[BirthDate]
      ,[MaritalStatus]
      ,[EmailAddress]
      ,[DateFirstPurchase]
  FROM [AdventureWorksDW2022].[dbo].[DimCustomer]
